@server_HostAddress = http://localhost:5176
@token = 

POST {{server_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "mahdi",
  "password": "password123",
  "email": "mahdi@dom.com",
  "firstName": "Mahdi",
  "lastName": "Abbasi"
}

###
POST {{server_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "mahdi",
  "password": "password123"
}

###
GET {{server_HostAddress}}/api/auth/me
Authorization: Bearer {{token}}
